---
title: "Untitled"
author: "Batuhan Arslan"
date: "10 Kasım 2019"
output: html_document
---
## First Step : Call Necessary Libraries

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(lubridate)
library(readxl)

```

## Download Data From Source
```{r}
tmp<-tempfile(fileext="BKM_data.xlsx")
download.file("https://github.com/pjournal/mef03-arslnbatu/blob/master/BKM_data.xlsx?raw=true",destfile=tmp,mode="wb")
BKM<-readxl::read_excel(tmp,skip=7,col_names=FALSE)
file.remove(tmp)
```
## Check What is

```{r}
head(BKM)
tail(BKM)
```
## Organize the Data 
```{r}
colnames(BKM) <- c("work_type","transection_item_credit","transection_item_debit","transection_cost_credit","transection_cost_debit","Dates")



```
## Analyze data
```{r}
new2 <- BKM %>% select(work_type,transection_item_credit,transection_item_debit,transection_cost_credit,transection_cost_debit)%>%group_by(work_type)%>%summarise(sum_credit=sum(transection_item_credit), sum_cost = sum(transection_cost_credit))%>%mutate(item_cost=(sum_credit/sum_cost))%>% arrange(desc(item_cost))
```

```{r}
new3 <- BKM %>% select(work_type,transection_item_credit,transection_item_debit,transection_cost_credit,transection_cost_debit)%>%group_by(work_type)%>%summarise(sum_debit=sum(transection_item_debit), sum_cost = sum(transection_cost_debit))%>%mutate(item_cost = round(sum_debit/sum_cost)) %>% arrange(desc(sum_debit))
```


```{r}
new4<- BKM  %>% group_by(work_type, Dates) %>% filter(work_type != "TOPLAM")%>%
  summarise(sum_debit=sum(transection_cost_debit)) %>% 
  arrange(desc(sum_debit))

  
```
## Show the analysis with data plotted 
```{r}
 ggplot(data = new4, aes(x = work_type, y = sum_debit, fill = work_type)) +
      geom_bar(stat = "identity") + theme(axis.text = element_text(angle = 0)) +  theme_bw() + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 0.5, size = 12))
 
```



## Compare transection_cost_debit and transection_cost_credit
```{r}
theme_set(theme_bw())  # pre-set the bw theme.
g <- ggplot(BKM, aes(transection_cost_debit, transection_cost_credit))
g + geom_jitter(width = .5, size=1) +
  labs(subtitle="compare", 
       y="cost debit", 
       x="cost credit", 
       title="analyze")

```
```{r}
library(scales)
theme_set(theme_classic())

# Plot
ggplot(new4, aes(x=work_type, y=sum_debit)) + 
  geom_point(col="tomato2", size=3) +   # Draw points
  geom_segment(aes(x=, 
                   xend=work_type, 
                   y=min(sum_debit), 
                   yend=max(sum_debit)), 
               linetype="dashed", 
               size=0.1) +   # Draw dashed lines
  labs(title="Dot Plot", 
       subtitle="Work type vs sum_debit", 
       caption="source: new4") +  
  coord_flip()

```

